"""Baseline test suite — pre-Bob-evolution.

These tests were written before Bob's analysis.  They pass on the correct
post-change implementation but contain demonstrably stale assertions and are
missing several acceptance cases:

  STALE  - test_premium_gets_a_discount: only asserts > 0, not the exact 15%
  STALE  - test_premium_discount_is_positive: redundant weak assertion
  MISSING - no test for Premium + Student (20% combination)
  MISSING - no test for Student-only invariant (0%)
  MISSING - no test for the $100 cap
  MISSING - no rounding boundary test

Preserved: zero-total test, negative-total test, non-premium zero test.

DO NOT EDIT this file after it has been snapshotted.
"""

from decimal import Decimal

import pytest

from sample_app.app.discounts import calculate_discount


# ---------------------------------------------------------------------------
# Preserved unaffected tests (still correct after the change)
# ---------------------------------------------------------------------------

class TestInputContract:
    def test_zero_total_premium(self):
        """Zero order total always returns zero discount."""
        result = calculate_discount(
            Decimal("0.00"), is_premium=True, is_student=False
        )
        assert result == Decimal("0.00")

    def test_zero_total_non_premium(self):
        result = calculate_discount(
            Decimal("0.00"), is_premium=False, is_student=False
        )
        assert result == Decimal("0.00")

    def test_negative_total_raises(self):
        with pytest.raises(ValueError):
            calculate_discount(
                Decimal("-1.00"), is_premium=True, is_student=False
            )

    def test_return_type_is_decimal(self):
        result = calculate_discount(
            Decimal("50.00"), is_premium=True, is_student=False
        )
        assert isinstance(result, Decimal)


class TestNonPremiumDiscount:
    def test_non_premium_no_discount(self):
        """Non-premium customer gets 0% discount."""
        result = calculate_discount(
            Decimal("100.00"), is_premium=False, is_student=False
        )
        assert result == Decimal("0.00")

    def test_return_two_decimal_places_non_premium(self):
        result = calculate_discount(
            Decimal("99.99"), is_premium=False, is_student=False
        )
        assert result == Decimal("0.00")


# ---------------------------------------------------------------------------
# Stale Premium tests — pass on correct code but don't pin the new rate
# ---------------------------------------------------------------------------

class TestPremiumDiscount:
    def test_premium_gets_a_discount(self):
        """STALE: only checks discount > 0, not that it equals 15%."""
        result = calculate_discount(
            Decimal("100.00"), is_premium=True, is_student=False
        )
        # This passes for the old 10% AND the new 15%; it does not distinguish them.
        assert result > Decimal("0.00")

    def test_premium_discount_is_positive(self):
        """STALE: redundant positivity check."""
        result = calculate_discount(
            Decimal("200.00"), is_premium=True, is_student=False
        )
        assert result > Decimal("0.00")
